Client/package-lock.json
Client/package.json
Client/src/App.jsx

Se ha instalado React-Router-Dom, para crear las rutas mas adelante, ya se pueden añadir Rutas a App.

Rutas App.jsx

---

Server/src/Models/Country.js
Server/src/Models/Empresas.js
Server/src/Models/Offers.js
Server/src/Models/Trainings.js
Server/src/Models/Users.js

Jccg models

---

Client/package-lock.json
Client/package.json
Client/src/App.jsx
Client/src/Redux/Reducers/Reducers.js
Client/src/Redux/Store.js
Client/src/Views/Login.jsx
Client/src/main.jsx

Se ha creado el Componente Login (aun no esta termiando) y se ha configurado la Store para poder utilizar Redux.

Componente Login y Configuracion Store

---

Server/src/Controller/createTrainingController.js
Server/src/Controller/getAllTrainingController.js
Server/src/Controller/getTrainingControllers.js
Server/src/Handler/createTrainingHandler.js
Server/src/Handler/getAllTraining.js
Server/src/Handler/getTrainingHandler.js
Server/src/Routes/index.js

Ya se pueden obtener las capacitaciones por nombre

Get training

---

Server/package-lock.json
Server/src/Controller/offersControllers.js
Server/src/Handler/offersHandler.js
Server/src/Models/Offers.js
Server/src/Routes/index.js

Controllers, handlers de offer
POST, GET, DELETE

Controller y handlers CRD modelo OFFER

---

Server/src/Controller/CountriesController.js
Server/src/Models/Cities.js
Server/src/Models/Countries.js
Server/src/Models/States.js
Server/src/Routes/index.js
Server/src/Tools/countries.json
Server/src/Tools/states.json
Server/src/db.js

primer avance paises db

---

Server/src/Controller/adminControllers.js
Server/src/Handler/loginHandler.js
Server/src/Models/admin.js
Server/src/Routes/index.js
Server/src/index.js

Debugg de handlres y controllers de adminSignUp y login

Jeff estructura back

---

Client/src/App.jsx
Client/src/Views/RegisterCompany.jsx

formulario para crear las empresas. falta: errores, validacion, paises para el select. falta probar pero necesito hacer la ruta.

registerCompany view

---

Server/src/Controller/CountriesController.js
Server/src/Controller/citiesController.js
Server/src/Controller/stateController.js
Server/src/Models/Cities.js
Server/src/Models/States.js
Server/src/Routes/index.js
Server/src/db.js
Server/src/index.js

[termine de hacer los modelos de countries stados y ciudades, modifique el nombre de los modelos ya que me estaban presnetando problemas con los json](https://github.com/CaravanaSocial/CaravanaSocial/pull/39)

modelos de ciudades listos

---

Server/src/Controller/adminControllers.js
Server/src/Controller/companiesControllers.js
Server/src/Controller/userController.js
Server/src/Handler/adminHandlers.js
Server/src/Handler/companiesHandlers.js
Server/src/Handler/userHandlers.js
Server/src/Routes/index.js

Segunda beta de correcciones de controladores y handlers de logueo y registrado.

Ken - Login/Sign-Up

---

Server/src/Controller/CountriesController.js
Server/src/Controller/citiesController.js
Server/src/Controller/stateController.js
Server/src/Handler/countryHanlder.js
Server/src/Routes/index.js
Server/src/index.js

automatizacion de la carga a la base de datos de los paises, se modifico index.js del servidor, para mejorar la fase de iniciacion de la base de datos

atomatizacion de la carga a la base de datos de los paises

---

Client/src/App.jsx
Client/src/Views/RegisterCompany/RegisterCompany.jsx
Client/src/Views/RegisterCompany/validation.js

moví el archivo a una carpeta y creé el validation. tambien actualicé la ruta en app. falta actualizar el form con las nuevas propiedades ( nombre, apellido, telefono, rubro de capacitacion, cargo) sigue faltando los paises para el select

registerCompany update

---

Server/src/Controller/companiesControllers.js
Server/src/Controller/userController.js
Server/src/Handler/adminHandlers.js
Server/src/Handler/companiesHandlers.js
Server/src/Handler/loginHandler.js
Server/src/Handler/userHandlers.js
Server/src/Routes/index.js

Crud de users/admins/companies (Sin terminar)

Crud de users/admins/companies (Sin terminar)

---

Server/src/Controller/createTrainingController.js
Server/src/Controller/patchTraining.js
Server/src/Controller/trainingDelete.js
Server/src/Handler/createTrainingHandler.js
Server/src/Handler/deleteTraining.js
Server/src/Handler/patchTraining.js
Server/src/Models/Companies.js
Server/src/Routes/index.js

Se agrego el delete y el patch

terminar CRUD training

---

Server/src/Controller/filterCountryController.js
Server/src/Handler/countryHanlder.js
Server/src/Handler/filterCountry.js
Server/src/Models/Cities.js
Server/src/Models/States.js
Server/src/Routes/index.js
Server/src/db.js
Server/src/index.js

termine de hacer los controladores de countries y states

Countriesdb

---

Server/src/Controller/filterCountryController.js
Server/src/Controller/offersControllers.js
Server/src/Controller/prefixesController.js
Server/src/Handler/countryHanlder.js
Server/src/Handler/filterCountry.js
Server/src/Handler/offersHandler.js
Server/src/Handler/prefixesHandler.js
Server/src/Models/Prefixes.js
Server/src/Tools/Prefixes.json
Server/src/db.js
Server/src/index.js

Se hace la funcion dentro de filterCountry donde se envia el codigo de pais junto con las ciudades del pais

Relacion Country Prefix - Jeff

---

Server/src/Routes/index.js

correccion 2

---

Server/src/Controller/companiesControllers.js

Cambio de nombre de variable (Sorry jeje)

---

Server/src/Controller/companiesControllers.js
Server/src/Models/Rubros.js
Server/src/db.js

Se implementó la funcionalidad para que las cuentas que se creen se vinculen con el rubro. Además de que cuando se haga un patch de una company, esta se "desrelacione" y se vuelva a relacionar con los nuevos parámetros brindados.

Relación rubro/company.

---

Server/src/Controller/rubroController.js
Server/src/Handler/rubrosHandler.js
Server/src/Routes/index.js

Creé un ruta para obtenerme los rubros y poder renderizarlos en el front.

Creación e implementación de una ruta getRubros

---

Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/RegisterCompany/RegisterCompany.jsx

rubros-phone

---

Server/src/Controller/prefixesController.js
Server/src/Handler/prefixesHandler.js
Server/src/Middlewares/validateAdminAccount.js
Server/src/Models/admin.js
Server/src/Routes/index.js

Agregué una ruta para las categorías y los prefijos. (Aún que los prefijos no los necesitemos)

Categories and Prefixes(deprecated)

---

Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js

falta solo el manejo de errores global :))))

listo register company

---

Server/package-lock.json
Server/package.json
Server/src/Handler/imageHandler.js
Server/src/Routes/Router.js
Server/src/Routes/imageRoute.js

config cloudinary

---

Server/src/Controller/Companies/getCompaniesController.js
Server/src/Controller/Companies/getCompanyAccController.js
Server/src/Middlewares/auth.js
Server/src/Middlewares/validateAdminAccount.js
Server/src/Routes/adminRoute.js

Include de categories para get companies

Include de categories para get companies

---

Server/src/Controller/Trainings/getCreatedTraining.js
Server/src/Controller/filterTrainings/filterTrain.js
Server/src/Handler/filterTrainingsHandler.js
Server/src/Routes/Router.js
Server/src/Routes/filterRoute.js

filter training

---

Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/RegisterCompany/RegisterCompany.jsx

register company TERMINADO

---

Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/Login/Login.jsx
Client/src/Views/RegisterUser/RegisterUser.jsx
Client/src/Views/RegisterUser/validation.js

login/registerUser errors :)

---

Client/index.html

cambie el logo de vite por el de caravana

pestaña iconlogo

---

Server/package-lock.json
Server/package.json
Server/src/Controller/Companies/createCompanyAccController.js
Server/src/Controller/Companies/getCompanyAccController.js
Server/src/Controller/User/createUserAccController.js
Server/src/Controller/User/getUserAccController.js
Server/src/Controller/User/getUsersController.js
Server/src/Controller/User/updateUserController.js
Server/src/Handler/imageHandler.js
Server/src/Middlewares/validateCompanyAccount.js
Server/src/Middlewares/validateUserAccount.js
Server/src/Models/Users.js
Server/src/Routes/Router.js
Server/src/Routes/companyRoute.js
Server/src/Routes/imageRoute.js
Server/src/Routes/userRoute.js
Server/src/db.js
package-lock.json

Diseñé los Middlewares de verificación para las cuentas de administrador, usuario y empresa.
También modifiqué modelos y relacioné los rubros con los usuarios.
Añadí los includes para las rutas gets que las cuentas relacionadas.

Middleware - Sign-Up / Include de Gets

---

Server/src/Controller/Admin/getAdminsByIdController.js
Server/src/Controller/Companies/getCompanyByIdController.js
Server/src/Controller/User/getUsersByIdController.js
Server/src/Handler/adminHandlers.js
Server/src/Handler/companiesHandlers.js
Server/src/Handler/userHandlers.js
Server/src/Routes/adminRoute.js
Server/src/Routes/companyRoute.js
Server/src/Routes/userRoute.js

Diseño de rutas para obtener cuentas por id.

Rutas byId para companies/ users / admins

---

Server/src/Controller/Offer/getOfferController.js
Server/src/Controller/Offer/postOfferController.js
Server/src/Handler/offersHandler.js
Server/src/Routes/offerRoute.js
Server/src/db.js

Jeff filtro offer

---

Client/src/Redux/Actions/Actions.js
Client/src/Views/RegisterCompany/RegisterCompany.jsx

y le puse un estilo basico a los rubros seleccionados jeje

rubros ruta arreglada

---

Client/src/Views/RegisterCompany/RegisterCompany.jsx
Client/src/Views/RegisterUser/RegisterUser.jsx

por ahora van todos a la misma vista

los registros llevan al home

---

Server/src/Controller/Offer/getOfferByIdController.js
Server/src/Controller/Trainings/getCreatedTraining.js
Server/src/Controller/Trainings/getTrainingByIdController.js
Server/src/Controller/User/getFreelancersController.js
Server/src/Handler/offersHandler.js
Server/src/Handler/trainingHandler.js
Server/src/Handler/userHandlers.js
Server/src/Routes/offerRoute.js
Server/src/Routes/trainingRoute.js
Server/src/Routes/userRoute.js

Empecé a crear la ruta byId de Offers

Empecé a crear la ruta byId de Offers

---

Server/src/Controller/Trainings/changer.js
Server/src/Controller/Trainings/delTraining.js
Server/src/Controller/Trainings/getAll.js
Server/src/Controller/Trainings/getCreatedTraining.js
Server/src/Controller/Trainings/getTrainingByIdController.js
Server/src/Controller/Trainings/getTrainingOnDb.js
Server/src/Controller/filterTrainings/filterTrain.js
Server/src/Handler/trainingHandler.js
Server/src/Routes/trainingRoute.js

correccion rutas training

---

Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/HomeUsers/HomeUsers.jsx
Client/src/Views/Login/Login.jsx
Client/src/Views/RegisterCompany/RegisterCompany.jsx
Client/src/Views/RegisterUser/RegisterUser.jsx
Client/src/components/NavBar.jsx

botones para crear

---

Client/src/Redux/Reducers/Reducers.js
Client/src/Views/CreateTrainings/CreateTrainings.jsx
Client/src/Views/HomeUsers/HomeUsers.jsx
Client/src/components/NavBar.jsx

ultimos cambios que se hicieron para la demo

---

Server/src/Controller/Freelancers/getFreelancerController.js
Server/src/Controller/Trainings/userToTrainingController.js
Server/src/Handler/freelancerHandler.js
Server/src/Handler/trainingHandler.js
Server/src/Routes/Router.js
Server/src/Routes/freelancerRoute.js
Server/src/Routes/trainingRoute.js
Server/src/Routes/userRoute.js

Filtros de Freelancer y rutas para GET

Freelancer GET & Filter

---

Server/src/Controller/User_training/userToTrainingController.js

arreglando mi cagada

---

Client/src/App.jsx
Client/src/Redux/Actions/Actions.js
Client/src/Views/UpdateProfile/ProfileUser.jsx
Client/src/components/CardFreelancer.jsx
Client/src/components/NavBar.jsx
Server/src/Controller/Admin/getAdminAccController.js
Server/src/Controller/Companies/createCompanyAccController.js
Server/src/Controller/Freelancers/getFreelancerController.js
Server/src/Controller/Offer/deleteOfferController.js
Server/src/Controller/Offer/postOfferController.js
Server/src/Controller/Questions/postQuestionController.js
Server/src/Controller/SuccessStories/changeStory.js
Server/src/Controller/Trainings/getCreatedTraining.js
Server/src/Controller/User/createUserAccController.js
Server/src/Handler/filterCountry.js
Server/src/Handler/freelancerHandler.js
Server/src/Handler/offersHandler.js
Server/src/Handler/prefixesHandler.js
Server/src/Handler/successHandler.js
Server/src/Handler/trainingHandler.js
Server/src/Routes/Router.js
Server/src/Templates/emailOffer.html
Server/src/Templates/emailRegisterCompany.html
Server/src/Templates/emailTraining.html

"Notificacion de Email Terminada, Register user, register company, offer y trainings"

Email notification

---

Client/src/Views/RegisterUser/validation.js
Client/src/Views/UpdateProfile/ProfileUser.jsx
Client/src/components/NavBar.jsx

falta debugear validaciones en actualizacion de perfil de usuario

navBar redirige a perfil, validaciones arregladas

---

Client/src/Views/UpdateProfile/ProfileCompany.jsx

update funcional (falta foto con cloudinary y estilos)

profile company, update

---

Server/src/Controller/cloudinary/cloudinaryWidgetController.js
Server/src/Handler/videoHandler.js
Server/src/Routes/Router.js
Server/src/Routes/videoRoute.js

creacion cloudinary back

---

Client/index.html
Client/package-lock.json
Client/package.json
Client/src/App.jsx
Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/CreateTrainings/CreateTrainings.jsx
Client/src/Views/CreateTrainings/Validation.js
Client/src/Views/CreateTrainings/videosTrainings.jsx
Client/src/components/UploadVideo.jsx
Server/src/Controller/Trainings/changer.js
Server/src/Controller/Trainings/getAll.js
Server/src/Controller/Trainings/getCreatedTraining.js
Server/src/Controller/cloudinary/cloudinaryWidgetController.js
Server/src/Handler/trainingHandler.js
Server/src/Handler/videoHandler.js
Server/src/Models/Trainings.js

Implementación de cloudinary para poder subir videos al crear capacitaciones.
Se creó una nueva vista en la que se subirán los videos posteriormente a la creación de la capacitación.
Además se modificaron varios controladores de trainings.

KenDev-Cloudinary

---

Client/src/App.jsx
Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/Home/Home.jsx
Client/src/Views/Users/FreelancerDetail.jsx
Client/src/components/CardFreelancer.jsx

Creación de la vida de detalle de los usuarios freelances

Creación de la vida de detalle de los usuarios freelances

---

Client/src/Views/CompanyDetail/CompanyDetail.jsx
Client/src/Views/UpdateProfile/ProfileCompany.jsx
Client/src/Views/UpdateProfile/ProfileUser.jsx
Client/src/components/NavBar.jsx

el componente de perfil de empresa ya puede actualizar su profile picture y muestra sus capacitaciones y ofertas de trabajo.
las capacitaciones llevan al detalle de las mismas y al detalle de la empresa al apretar el nombre.

retoques en el renderizado de las capacitaciones

---

Server/src/Controller/Companies/getCompaniesController.js
Server/src/Controller/Companies/getCompanyAccController.js
Server/src/Controller/Companies/getCompanyByIdController.js
Server/src/Controller/Companies/updateCompanyController.js
Server/src/Controller/User/getFreelancersController.js
Server/src/Controller/User/getUsersController.js

Se agregaron includes de las diferentes relaciones.

Modificación y actualización de controladores de cuentas

---

Server/src/Controller/Trainings/aproveTriningController.js
Server/src/Templates/trainingApproved.html
Server/src/Templates/trainingDeclined.html

Email declined and approved implemented

email trainig approved and declined

---

Client/src/App.jsx
Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/Admin/AdminDashboard.jsx
Client/src/Views/Trainings/TrainingDatail.jsx

admin dashboard

---

Client/src/App.jsx
Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/Admin/AdminDashboard.jsx
Client/src/Views/Faq/Faq.jsx
Client/src/Views/Home/Home.jsx
Client/src/Views/Trainings/TrainingDatail.jsx
Client/src/Views/Trainings/Trainings.jsx
Client/src/components/AdminViews/EditQAndA.jsx
Client/src/components/AdminViews/QAndA.jsx

Terminamos la aprobación y rechazo de las capacitaciones, incluyendo renderiza de botones según el estado de la capacitación, además de hacer que sólo se pueda realizar desde una cuneta de administrador.
Se implementó la vista de Q&A y se pueden editar. <3 (Con Enzo)

Aprobación de capacitaciones terminada / Vista y editar de Q&A (Con Enzo)

---

Client/src/Views/Home/Home.jsx
Client/src/Views/Offers/Detail/DetailOffer.jsx

Se agregó un conditional chaining en offer.areaTraining.map porque no dejaba leer propiedades de undefined map.

Offer detail fixed

---

Client/src/Views/CreateJobs/CreateJobs.jsx
Client/src/Views/Offers/Detail/DetailOffer.jsx
Client/src/components/Offercard.jsx

Debugged de offers, Deatail, card y createJob

Jeff offers

---

Server/src/Controller/SuccessStories/changeStory.js
Server/src/Controller/SuccessStories/createSuccSto.js
Server/src/Handler/successHandler.js
Server/src/Models/SuccessStory.js
Server/src/Routes/successStoriesRoute.js

success stories

---

Client/src/Views/Trainings/TrainingDatail.jsx
Client/src/components/AdminViews/Accounts.jsx
Server/src/Controller/Admin/createAdminAccController.js
Server/src/Controller/Admin/getAdminAccController.js
Server/src/Controller/Admin/getAdminsByIdController.js
Server/src/Controller/Admin/getAdminsController.js
Server/src/Controller/Admin/updateAdminController.js
Server/src/Controller/Companies/getCompaniesController.js
Server/src/Controller/Offer/postOfferController.js
Server/src/Controller/Trainings/getCreatedTraining.js
Server/src/Controller/User/getUsersController.js
Server/src/Handler/companiesHandlers.js
Server/src/Handler/loginHandler.js
Server/src/Handler/offersHandler.js
Server/src/Handler/userHandlers.js
Server/src/Models/admin.js
Server/src/Routes/userRoute.js
Server/src/db.js

Se implementó la funcionalidad de que las cuentas de adminsitrador puedan crear capacitaciones y ofertas de trabajo. Asimismo estas se relacionan y se incluyen entodos los gets de todas sus rutas.
Actualizó la ruta de get de companies y users para que mediante un query ?value= se pueda obtener tanto las cuentas eliminadas como las que no.

Admin create-trainings/jobs | getDeleted (user/companies)

---

Server/src/Controller/Blog/deleteBlogController.js
Server/src/Controller/Blog/getAllBlogController.js
Server/src/Controller/Blog/getByIdController.js
Server/src/Controller/Blog/patchBlogController.js
Server/src/Controller/Blog/postBlogController.js
Server/src/Handler/blogHandler.js
Server/src/Models/blog.js
Server/src/Routes/Router.js
Server/src/Routes/blogsRoute.js
Server/src/db.js

Todo el CRUD de blog esta hecho

Rutas Blog

---

Client/src/Views/UpdateProfile/ProfileCompany.jsx

estilo profile company

---

Client/src/Views/UpdateProfile/ProfileCompany.jsx
Client/src/Views/UpdateProfile/ProfileUser.jsx

listo con darkmode y responsive
retoqué unas cositas del detail de empresa

update user estilo

---

Server/src/Controller/Companies/getCompanyByNameController.js
Server/src/Controller/Offer/getOfferByNameController.js
Server/src/Controller/User/getUserByNameController.js
Server/src/Handler/companiesHandlers.js
Server/src/Handler/offersHandler.js
Server/src/Handler/userHandlers.js
Server/src/Routes/companyRoute.js
Server/src/Routes/offerRoute.js
Server/src/Routes/userRoute.js

Rutas Search

---

Client/src/Views/LandingPage.jsx

le agregué botones para el registro

retoques de estilo en la landing

---

Client/src/Views/CompanyDetail/CompanyDetail.jsx
Client/src/Views/Home/Home.jsx
Client/src/Views/Trainings/CardTrainings.jsx
Client/src/components/Offercard.jsx

retoques de estilos

---

Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/Admin/AdminDashboard.jsx
Client/src/components/AdminViews/Admins/Admins.jsx
Client/src/components/AdminViews/Admins/validations.js
Client/src/components/AdminViews/Companies.jsx
Client/src/components/AdminViews/QAndA.jsx
Client/src/components/AdminViews/Users.jsx
Server/src/Controller/Admin/getAdminsController.js
Server/src/Controller/Companies/getCompaniesController.js
Server/src/Controller/User/getUsersController.js

botones y renderizado de eliminar y restaurar usuarios, empresas y admins y form y validaciones para crear admins terminado

eliminar y restaurar usuarios, empresas y admins listos y form de crear admins

---

Client/src/components/NavBar.jsx

se quito el searchbar de register user y register company

---

Client/src/Redux/Actions/Actions.js
Client/src/Views/Verification/Verification.jsx
Server/src/Controller/Companies/createCompanyAccController.js
Server/src/Controller/Login/loginController.js
Server/src/Controller/Login/loginGoogleController.js

Implementación de verificación de email para cuentas de empresa.
Se añadieron dos propiedades a los modelos de user y de company. A la hora de la creación de ambos se genera un código aleatorio que se almacena en una variable llamada verificationCode. Asimismo la cuenta se crea con un bool llamado verified inicializado en false.
Al crearse la cuenta se envía un mail con el codigo de verificación. y el link en donde se debe ingresar dicho codigo.
Al ingresar el codigo y se verifique que este coincida con el generado anteriormente se le hace un patch a la cuenta de su propiedad verified para que se establezca en true.
Por ende el logueo dejará ingresar.
(Además manejó el error de si se ingresa un código incorrecto)

Implementación de verificación de email para cuentas de empresa

---

Client/src/App.jsx
Client/src/Views/Verification/Verification.jsx
Server/src/Controller/Companies/createCompanyAccController.js
Server/src/Controller/User/createUserAccController.js
Server/src/Templates/emailRegister.html
Server/src/Templates/emailRegisterCompany.html

Verificación con un click y actualización de templates

Verificación con un click y actualización de templates

---

Client/src/Views/Login/Login.jsx
Server/src/Controller/Admin/updateAdminController.js
Server/src/Controller/Login/loginController.js

Solución de inicio de sesión con google y el sweet alert con login de google

Ken / Solución de inicio de sesión con google y el sweet alert con login de google

---

Client/src/Views/RegisterCompany/RegisterCompany.jsx
Client/src/Views/RegisterCompany/validation.js
Client/src/Views/RegisterUser/RegisterUser.jsx
Client/src/Views/Users/FreelancerDetail.jsx
Client/src/components/CardFreelancer.jsx

otras cosas: boton para volver desde el detalle de un freelancer, tipografia de los registros, tipografia de la descripcion de la card de freelancer en home

register company doble input email y otras cosas

---

Client/src/Views/CreateJobs/CreateJobs.jsx
Client/src/Views/CreateTrainings/CreateTrainings.jsx
Client/src/Views/Home/Home.jsx
Client/src/Views/LandingPage.jsx
Client/src/Views/Login/Login.jsx
Client/src/Views/PasswordRecovery/PasswordRecovery.jsx
Client/src/Views/UpdateProfile/ProfileCompany.jsx
Client/src/Views/UpdateProfile/ProfileUser.jsx
Client/src/Views/Verification/Verification.jsx

Texto a voz en varios componentes y error fixes

Texto a voz en varios componentes y error fixes

---

Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/Trainings/TrainingDatail.jsx
Server/src/Routes/commentRoute.js

delete comments funcional

---

Client/src/Views/RegisterUser/RegisterUser.jsx
Server/src/Controller/User/createUserAccController.js

ya se pueden agregar certificados como links

certificados del registro de usuario arreglado

---

Client/src/Redux/Actions/Actions.js
Client/src/Redux/Reducers/Reducers.js
Client/src/Views/Admin/AdminDashboard.jsx
Client/src/Views/Freelancers/Freelancers.jsx
Client/src/components/Blog/BlogCard.jsx
Client/src/components/Blog/BlogDetail.jsx
Client/src/components/Blog/BlogHub.jsx
Client/src/components/Blog/PresetBlog.jsx
Client/src/components/Blog/PresetBlog.module.css
Client/src/components/NavBar.jsx
Server/src/Controller/Freelancers/getFreelancerController.js
Server/src/Handler/blogHandler.js
Server/src/Handler/freelancerHandler.js
Server/src/Models/blog.js

Se agrego Blog al Dashboard de Admin y se arreglo filtro de Freelancers

Update Blog, Freelancer filter

---

Client/src/Redux/Reducers/Reducers.js
Client/src/Views/Offers/Detail/DetailOffer.jsx
Client/src/components/NavBar.jsx

Invertido toggle de voz, boton crear casos de exito y boton de aplicar en offers se ha borrado

---

Client/src/Views/CreateTrainings/videosTrainings.jsx
Client/src/Views/Freelancers/Freelancers.jsx
Client/src/Views/Offers/Offers.jsx
Client/src/Views/RegisterUser/validation.js
Client/src/Views/Trainings/CardTrainings.jsx
Client/src/Views/Trainings/TrainingDatail.jsx
Client/src/Views/Trainings/Trainings.jsx

se hicieron cositas

---

Client/src/Views/Offers/Offers.jsx
Server/src/Controller/Offer/getOfferByNameController.js

coneccion de filtros offer

---

Client/src/Redux/Actions/Actions.js
Server/src/db.js

cambio deploy

---

Server/src/Controller/filterTrainings/filterTrain.js
Server/src/db.js

filtros capacitaciones

---

Client/src/Views/CompanyDetail/CompanyDetail.jsx
Client/src/Views/Freelancers/Freelancers.jsx
Client/src/Views/LandingPage.jsx
Client/src/Views/Offers/Detail/DetailOffer.jsx
Client/src/Views/Offers/Offers.jsx
Client/src/Views/Trainings/TrainingDatail.jsx
Client/src/Views/Trainings/Trainings.jsx
Client/src/Views/UpdateProfile/PasswordChange.jsx
Client/src/components/SuccessCard.jsx

botones volver, y mas arreglos de estilo

---

Client/src/Views/Freelancers/Freelancers.jsx
Client/src/Views/Home/Home.jsx
Client/src/Views/Offers/Offers.jsx
Client/src/Views/Trainings/CardTrainings.jsx
Client/src/Views/Trainings/TrainingDatail.jsx
Client/src/Views/Trainings/Trainings.jsx
Client/src/Views/Users/FreelancerDetail.jsx
Client/src/components/CardFreelancer.jsx
Client/src/components/Offercard.jsx
Client/src/components/Slider.jsx

vista home y vista de ver mas.
falta responsive y darle detalles al detail de todas

estilos de las cartas

---

Client/src/Redux/Actions/Actions.js
Server/src/Controller/User/updatePassUserController.js
Server/src/Handler/userHandlers.js
Server/src/db.js

Letrero error en cambio de contraseña
